### ISSUE TITLE
last braille extender update dev is not loading

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#11]
WARNING - external:globalPlugins.brailleExtender.configBE.checkConfigPath (12:00:41.049):
`C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles/handyTech/profile.ini` not found or is inaccessible
ERROR - globalPluginHandler.listPlugins (12:00:41.049):
Error importing global plugin brailleExtender
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 22, in listPlugins
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 46, in <module>
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\configBE.py", line 313, in <module>
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\configBE.py", line 100, in loadConf
KeyError: 'miscs'
INFO - core.main (12:00:41.078):
NVDA initialized

**Comment by Andre9642** [comment]
Hi, could you test with the current [latest version](https://github.com/Andre9642/BrailleExtender/releases/download/untagged-218deb1a65de1983c90d/BrailleExtender-dev-18.01.17-200714.nvda-addon) please? :)

**Comment by zstanecic** [comment]
Hi,
Tested and getting the same
Now the Braille display is loaded without the profile in Braille extender,
So it says that there is no gesture map, but without the profile forgot that you cancustomize role abbreviations or add the Braille tables to rotor because o tables was not defined.
See the log.
ERROR - unhandled exception (21:40:43.236):
Traceback (most recent call last):
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 380, in onAddOutputTableInSwitch
NameError: global name 'oTables' is not defined
The same is with the imput table rotor
ERROR - unhandled exception (21:43:29.365):
Traceback (most recent call last):
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 648, in onAddInputTableInSwitch
NameError: global name 'iTables' is not defined

Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: środa, 17 stycznia 2018 21:14
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] last braille extender update dev isnot loading (#11)

Hi, could you test with the current latest version please? :)

**Comment by Andre9642** [comment]
Is it better with [this build](https://github.com/Andre9642/BrailleExtender/releases/download/untagged-218deb1a65de1983c90d/BrailleExtender-dev-18.01.17-205939.nvda-addon)?
For customize role abbreviations, it's not finish yet.
Concerning the customization of role abbreviations, it's not finished yet. Coming soon!
Thanks for your help!

**Comment by zstanecic** [comment]
Yes, it is better.
I am updating my builds locally using github and scons, so whenever you make a change, i see it instantly by fetching your master to my master.
And, before i send you the PR with the translation, i test the translation by compiling your code locally.


Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: środa, 17 stycznia 2018 22:08
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] last braille extender update dev isnot loading (#11)

Is it better with this build?
For customize role abbreviations, it's not finish yet.
Concerning the customization of role abbreviations, it's not finished yet. Coming soon!
Thanks for your help!

**Comment by zstanecic** [comment]
And, i will 
Always help you, as there are braillists, wich will benefit from your work.
As this problem is solved,
I propose closing this ticket.
Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: środa, 17 stycznia 2018 22:08
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] last braille extender update dev isnot loading (#11)

Is it better with this build?
For customize role abbreviations, it's not finish yet.
Concerning the customization of role abbreviations, it's not finished yet. Coming soon!
Thanks for your help!
