### ISSUE TITLE
when in microsoft word, atribra is not working

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#14]
microsoft word version,
16.0.4639.1000)
latest master version of NVDA
try to turn on braille extender and attribra to indicate bold or italic
result when doing bold or italic, it is not working

**Comment by Andre9642** [comment]
Hello,
Thanks for this report.
In Attribra tab, There is a specific profile for Microsoft Word.
Have you checked the corresponding checkboxes?
If yes, could you me send your attribra-BE.ini (located at the root of your NVDA user folder) please?
Thanks again,

**Comment by zstanecic** [comment]
Yes, i checked all checkboxes and configured all profiles
Soon you will get the ini file from my directory
Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: środa, 28 marca 2018 18:29
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] when in microsoft word, atribra isnot working (#14)

Hello,
Thanks for this report.
In Attribra tab, There is a specific profile for Microsoft Word.
Have you checked the corresponding checkboxes?
If yes, could you me send your attribra-BE.ini (located at the root of your NVDA user folder) please?
Thanks again,

**Comment by Andre9642** [comment]
Is it the same thing for underline and spelling error?

**Comment by zstanecic** [comment]
yes it is.
the same... it is not working for some reason

here is the content of the file, as the sysem is not allowing me to attach it directly.
# Attribra for BrailleExtender
# Thanks to Alberto Zanella
# -> https://github.com/albzan/attribra/

[eclipse]
underline = 1
invalid-spelling = 1
bold = 1
italic = 1
background-color = "rgb(24420045)", "rgb(2550128)"

[firefox]
color = "RGB(255, 0, 0)"
invalid-spelling = 1
bold = 1
italic = 1
underline = 1

[global]
invalid-spelling = 1
bold = 1
italic = 1
underline = 1

[thunderbird]
invalid-spelling = 1
bold = 1
italic = 1
underline = 1

[winword]
invalid-spelling = 1
bold = 1
italic = 1
underline = 1

**Comment by Andre9642** [comment]
Thank you, I'll investigate this asap.
Unfortunately, currently, I can't reproduce this with Microsoft Word Office 2016 16.0.9029.2253...

**Comment by zstanecic** [comment]
hi. maybe ićve found the error with attribra
the thunderbird seettings were reset to defaults, too
with the error 
WARNING - external:globalPlugins.brailleExtender.configBE.loadConf (15:57:46.987):
C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\handyTech\default\profile.ini inaccessible
WARNING - external:globalPlugins.brailleExtender.configBE.initGestures (15:57:46.987):
No main gestures map (C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\handyTech\default\gestures.ini; C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\handyTech\default\gestures.ini) found

**Comment by zstanecic** [comment]
profiles editor is not opening, too
ERROR - unhandled exception (16:32:18.440):
Traceback (most recent call last):
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 1287, in onEditProfileGestures
  File "gui\__init__.pyc", line 186, in _popupSettingsDialog
  File "gui\settingsDialogs.pyc", line 92, in __init__
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\editProfileGestures.py", line 95, in postInit
ValueError: u'default' is not in list

**Comment by Andre9642** [comment]
I think that I found the problem for Attribra. Could you try with the latest commit please?
Concerning profiles editor, it is not finished yet. Currently, I haven't much time.. :(
Thanks

**Comment by zstanecic** [comment]
Hi andre,
No, it is not working, even with the last commit

Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: niedziela, 1 kwietnia 2018 23:04
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] when in microsoft word, atribra isnot working (#14)

I think that I found the problem for Attribra. Could you try with the latest commit please?
Concerning profiles editor, it is not finished yet. Currently, I haven't much time.. :(
Thanks

**Comment by Andre9642** [comment]
Which output braille table do you work with?

**Comment by zstanecic** [comment]
Russian 8 dots, my modified one,
And polish 8 dots.
No matter which Braille table i use, it simply doesn’t work.


Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: poniedziałek, 2 kwietnia 2018 00:26
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] when in microsoft word, atribra isnot working (#14)

Which output braille table do you work with?

**Comment by Andre9642** [comment]
OK, thanks. I was able to reproduce your issue with the Russian 8 dots table.
With the Last Commit, it's good for me now. But that does not mean it's good for everyone :) Is it better for you?
Thanks

**Comment by zstanecic** [comment]
yes, now it works,
thanks.
it works with all tables which i use, including croatian, russian and polish.
the latest commit fixed the problem.
Can you describe technically, where was the problem?
and here is the my modified russian table which i use.
it works on cyrillic imput and output, and it has defined  all chars.
[ru-compbrl.log](https://github.com/Andre9642/BrailleExtender/files/1866781/ru-compbrl.log)

remove log extension and rename it to ctb, and replace this table with the my one if you want to test it further

**Comment by Andre9642** [comment]
OK thanks, great. But I found another issue.
When a character is represented on several braille cells, there is a gap with the highlighting of dots 7 and 8... I'll study this ASAP.
Thanks for your table. This gives me the idea to allow to use its own input / output tables. And why not include alternative tables like yours?
