### ISSUE TITLE
Should routing by cursor key emulation be configurable

### ISSUE THREAD

**Issue by daniel-1964** [Andre9642/BrailleExtender#20]
Some applications like Emacs under cygwin or some Linux app through putty or mintty handle mouse.
With the latest stable version of braille extender (I.E. 2018-08-14), theses apps stop working properly when I use routing cursor.
If I disable the keyboard movement emulator in patch.py by the following:
if 0 and obj.hasFocus and braille.handler._cursorPos and (obj.role == controlTypes.ROLE_TERMINAL or (obj.role == controlTypes.ROLE_EDITABLETEXT and braille.handler.tether == braille.handler.TETHER_REVIEW)):
The mouse aware apps rework but I loose the keyboard emulator for routing cursor.
So I suggest a config flag to enable and disable this feature as appropriate.
Something like:
if config.conf["brailleExtender"]['EmulateRouting'] and obj.hasFocus and braille.handler._cursorPos and (obj.role == controlTypes.ROLE_TERMINAL or (obj.role == controlTypes.ROLE_EDITABLETEXT and braille.handler.tether == braille.handler.TETHER_REVIEW)):
Could work fine.

**Comment by Andre9642** [comment]
Hi,
Thanks for this suggestion. Feel free to create a pull request if you want!
