### ISSUE TITLE
One-hand mode feature

### ISSUE THREAD

**Issue by Andre9642** [Andre9642/BrailleExtender#40]
First, add an option to pick up between left hand or right hand.

Then, in practice:

If I want to type ⠛:
- left-hand mode: enter dots 12, then 12
- right-hand mode: enter dots 45, then 45

If I want to type ⠇:
- left-hand mode: enter dots 123, then space
- right-hand mode: enter dots 456 then space

If I want to type ⠸:
- left-hand mode: press space, then enter dots 123
- right-hand mode: press space, then dots 456

For shortcuts and other gestures: TBD

**Comment by Afik-souffir998** [comment]
hi, this is a great fiture.

**Comment by Andre9642** [comment]
Hi @Afik-souffir998,
I started to work around this functionality.
You can test with this try build <https://andreabc.dev/projects/NVDA_addons/BrailleExtender/BrailleExtender-test-oneHandMode.nvda-addon>

You'll find this feature in general settings of the add-on. There are 3 input methods (only two work currently).

Your comment are welcome!

**Comment by Andre9642** [comment]
Some input examples:

#### With method 1: fill a cell in two stages on both sides
* To send ⠛, you can press:
	* Dots 1-2 then dots 4-5.
	* Dot 1 then dots 2-4-5.
	* Etc.
* To send ⠃, you can press:
	* Dots 1-2 then 1-2.
	* Dot 1 then dot 2.
	* Dot 1 then dots 1-2.
	* Etc.
* To send ⠘, you can press:
	* Dots 4-5 then 4-5.
	* Dot 4 then dot 5.
	* Etc.

#### With method 2: fill a cell in two stages on one side
* To send ⠛, you can press:
	* dots 1-2 then dots 1-2
	* dots 4-5 then dots 4-5
	* dots 1-2 then dots 4-5
	* dots 4-5 then dots 1-2
* To send ⠃, you can press:
	* Dots 1-2 then space.
	* Dots 4-5 then space.
* To send ⠘, you can press:
	* Dots space then 1-2.
	* Dots space then 4-5.
* To send ⠀, you must press space 2 times.

#### With method 3: fill a cell dots by dots

Each dot is a toggle, press space to validate the character.  
To send ⠛, you can press:

* Dots 1-2, then dots 4-5, then space.
* Dots 1-2-3, then 3 (to correct), then dots 4-5, then space.
* Dot 1, then dots 2-4-5, then space.
* Dots 1-2-4, then dot 5, then space.
* Dot 2, then dot 1, then dot 5, then dot 4, then space.
* Etc.
