### ISSUE TITLE
braille extender refuses to save settings when changing braille representation settings of unknown characters

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#49]
Try to change the braille representation settings and it will crach andrefuse to close the dialog, 

Log complaints about the unregistered setting

**Comment by Andre9642** [comment]
Hi,
I can't reproduce this bug. Can you give more details and log please?
Thanks

**Comment by zstanecic** [comment]
1.	Open settings, then braille tables
2.	In the undefined braille characters representation select use dots 25 questionmark, 
3.	Press ok.
4.	ERROR - globalPluginHandler.initialize (22:04:39.979) - MainThread (7664):
5.	Error initializing global plugin <class 'globalPlugins.brailleExtender.GlobalPlugin'>
6.	Traceback (most recent call last):
7.	  File "globalPluginHandler.pyc", line 33, in initialize
8.	  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 185, in __init__
9.	    self.reloadBrailleTables()
10.	  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 306, in reloadBrailleTables
11.	    patchs.setUndefinedChar()
12.	  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patchs.py", line 163, in setUndefinedChar
13.	    v = huc.unicodeBrailleToDescription(getTextInBraille(s, getCurrentBrailleTables()))
14.	  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\utils.py", line 255, in getTextInBraille
15.	    else: table = [os.path.join(brailleTables.TABLES_DIR, table)]
16.	  File "ntpath.pyc", line 115, in join
17.	  File "genericpath.pyc", line 153, in _check_arg_types
18.	TypeError: join() argument must be str or bytes, not 'list'
19.	INFO - core.main (22:04:40.140) - MainThread (7664):

**Comment by Andre9642** [comment]
Thanks a lot for these details. it should work now :)

**Comment by zstanecic** [comment]
This issue is successfully fixed in the latest dev version.
It even broke the braille extender on start, respectively.
