### ISSUE TITLE
Undefined character representation and text descriptions features not working correctly together

### ISSUE THREAD

**Issue by pitermach** [Andre9642/BrailleExtender#54]
NVDA 2019.3.1, Braille Extender 20.04.20:296059c, with the Polish 8-dot computer braille table.

Having both the option to have both a different undefined character representation as well as descriptions of undefined characters checked doesn't seem to give correct results, or at least the options don't work how I expect. Here's what I'm seeing with a few combinations:

- With representation set to one of the options that display the character codes, like HUC6/8, Binary, etc, and descriptions unchecked, the feature works and I always get representations in whatever style I selected from the ones above.
- With representation set to the same options as above but also with descriptions checked, the undefined characters always get displayed with liblouis style hex codes, and if a character has a description, it gets displayed as well surrounded by more hex codes. The characters set to indicate start and end of a description seem to be never used.
- With representation set to any of the other options (question mark, empty cell, custom pattern, etc) no matter whether descriptions are checked or not, every undefined character gets displayed with a start and end tag with nothing inside it, even if the character does have a description.

What I would expect to happen is that for characters that have a description I'd just see the description surrounded by the start and end tags, otherwise you'd get the undefined representation. If this isn't how the feature is supposed to work feel free to correct me on this, though in that case I think that should be explained somewhere.

**Comment by pitermach** [comment]
I just tried this again with Braille Extender 20.05.03:976a7a0, and I'm happy to say that the first problem appears to be fixed, so with the representation set to HUC8 for example and with the character descriptions checked, I now get the HUC8 representation for a character if it doesn't have a description, or its description surrounded by the start and end tag if it does. This is how I wanted to use this feature so that's great!

However, the second problem I listed, where if you have the representation method set to any of the other options, like question mark or empty cell, no matter whether you have the descriptions on or not, all you get is an empty start and end tag instead of the character representation, is still there so I'll leave this issue open for now.

**Comment by Andre9642** [comment]
((Sorry for the delay! I've been quite busy lately and I had no time to dedicate to Braille Extender.))
Thank for the report. I'll try to improve this soon. The last dev version contains some translation  updates only.

**Comment by Andre9642** [comment]
Is it better with the latest dev version?
I know that there is an issue with a contracted braille table and cursor positions in some cases. I'll try to fix later.
Thanks

**Comment by pitermach** [comment]
Yep, everything works great now. Thanks for the fix, this feature is really useful. 
Since the main issue I described is fixed I'm going to close this now as I'm mainly working with an uncontracted table, but if you want it to stay open until the cursor problem you mentioned is also fixed, in which case you can reopen it.
