### ISSUE TITLE
Code restructuring: properly port Braille Extender to Python 3, remove Python 2 idioms and facilities

### ISSUE THREAD

**Issue by josephsl** [Andre9642/BrailleExtender#69]
Hi,

A high priority blocker for #68 

Before linting can proceed, it is important to port Braille Extender to Python 3. This is because add-on manifest says NVDA 2019.3 is the minimum supported version, and NVDA Core expects Python 3.7 or later.

The following will be done:

* Remove Python 2 checks
* Remove unicode literals import directive
* Many more

Thanks.

**Comment by Andre9642** [comment]
Hi @josephsl,

> - Remove Python 2 checks
> - Remove unicode literals import directive

I think all these are done.

> - Many more

Could you elaborate on this? Perhaps it's better to close this issue and open others.

Thanks

**Comment by josephsl** [comment]
Hi, pretty much most of these are done. Let’s open new issues for others.
