### ISSUE TITLE
rotor under dev with focus braille-display don't work

### ISSUE THREAD

**Issue by christopherpross** [Andre9642/BrailleExtender#86]
Hey,
If I try to press dot2+dot3+spacebar or dot5+dot6+spacebar to rotate the rotor, nothing happens here.
Nvda 2020.2
braille extender: dev-channel
braille-display: focus 40 blue from frindom scintific 

here is a log snipped:

DEBUG - brailleDisplayDrivers.freedomScientific.BrailleDisplayDriver._onReceive (11:42:34.195) - braille._BgThread (264436):
Got packet of type b'\x03' with args: b'\x00' b'\x80' b'\x00'
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture (11:42:34.195) - braille._BgThread (264436):
Input: br(freedomScientific.Focus40):dot2+dot3+brailleSpaceBar
DEBUG - speech.manager._speechManagerUnitTest (11:42:34.210) - MainThread (75456):
SpeechManager- Cancel
DEBUG - audioDucking.AudioDucker.disable (11:42:34.210) - MainThread (75456):
Ignoring duplicate disable
ERROR - scriptHandler.executeScript (11:42:34.210) - MainThread (75456):
error executing script: <bound method GlobalPlugin.script_priorRotor of <globalPlugins.brailleExtender.GlobalPlugin object at 0x0AE8C3B0>> with gesture 'Leerzeichen mit Punkt 2 3'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "C:\Users\Christopher Pross\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 314, in script_priorRotor
    if rotorItem > 0:
NameError: name 'rotorItem' is not defined
DEBUG - hwIo.IoBase._notifyReceive (11:42:34.305) - braille._BgThread (264436):
Read: b'\x03\x06\x80\x00'
DEBUG - brailleDisplayDrivers.freedomScientific.BrailleDisplayDriver._onReceive (11:42:34.305) - braille._BgThread (264436):
Got packet of type b'\x03' with args: b'\x06' b'\x80' b'\x00'
DEBUG - hwIo.IoBase._notifyReceive (11:42:34.389) - braille._BgThread (264436):
Read: b'\x03\x00\x80\x00'
DEBUG - brailleDisplayDrivers.freedomScientific.BrailleDisplayDriver._onReceive (11:42:34.390) - braille._BgThread (264436):
Got packet of type b'\x03' with args: b'\x00' b'\x80' b'\x00'
IO - external:globalPlugins.brailleExtender.patches.InputManager.executeGesture (11:42:34.390) - braille._BgThread (264436):
Input: br(freedomScientific.Focus40):dot2+dot3+brailleSpaceBar
ERROR - scriptHandler.executeScript (11:42:34.416) - MainThread (75456):
error executing script: <bound method GlobalPlugin.script_priorRotor of <globalPlugins.brailleExtender.GlobalPlugin object at 0x0AE8C3B0>> with gesture 'Leerzeichen mit Punkt 2 3'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "C:\Users\Christopher Pross\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 314, in script_priorRotor
    if rotorItem > 0:
NameError: name 'rotorItem' is not defined

**Comment by Andre9642** [comment]
Hello,
Thanks for the report.
This feature is currently reimplementing. See PR #80.

**Comment by christopherpross** [comment]
It is fixed for me, so I close that here. ☺️
