### ISSUE TITLE
The bug with undefined characters

### ISSUE THREAD

**Issue by Futyn-Maker** [Andre9642/BrailleExtender#99]
Hello!

It's probably the result of wrong interraction of the addon with Liblouis. When I read texts and meet a specific symbol which is not defined in the Braille table, my focus-40 Braille display is disconnected at all. The most strange thing is that this bug appears not with all undefined symbols and not with all Braille tables.

Example (NVDA 2020.3):
1. Choose the Ukrainian grade 1 table or the Uzbek, which includes ru-litbrl.ctb;
2. In any text editor put the symbol `·` (u+00B7) and try to read it with a Braille display. Th' 'ymbol isn't defined in the table;
3. See the bug.

It's not the only symbol, just for example. When i switch off the addon, the bug disappears. Here's the NVDA-log in the moment of this bug.

INFO - braille.BrailleHandler.setDisplayByName (12:31:34.550) - braille._BgThread (9852):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - braille.BrailleHandler.setDisplayByName (12:31:40.264) - braille._BgThread (9852):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - braille.BrailleHandler.setDisplayByName (12:31:45.394) - braille._BgThread (9852):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleDisplayDrivers.freedomScientific.BrailleDisplayDriver.__init__ (12:31:52.260) - braille._BgThread (9852):
Found Focus 40 connected via serial (COM3)
INFO - braille.BrailleHandler.setDisplayByName (12:31:52.274) - braille._BgThread (9852):
Loaded braille display driver freedomScientific, current display has 40 cells.
WARNING - external:globalPlugins.brailleExtender.undefinedchars.getExtendedSymbolsForString (12:31:52.302) - MainThread (15924):
Unable to load extended symbols for: Windows, using english
INFO - brailleDisplayDrivers.freedomScientific.BrailleDisplayDriver.__init__ (12:31:55.120) - braille._BgThread (9852):
Found Focus 40 connected via serial (COM3)
INFO - braille.BrailleHandler.setDisplayByName (12:31:55.126) - braille._BgThread (9852):
Loaded braille display driver freedomScientific, current display has 40 cells.
ERROR - braille.executor (12:31:59.284) - braille._BgThread (9852):
Error displaying cells. Disabling display
Traceback (most recent call last):
  File "braille.pyc", line 2163, in executor
  File "brailleDisplayDrivers\freedomScientific.pyc", line 500, in display
ValueError: bytes must be in range(0, 256)
ERROR - braille.BrailleHandler.handleDisplayUnavailable (12:31:59.284) - braille._BgThread (9852):
Braille display unavailable. Disabling
Traceback (most recent call last):
  File "braille.pyc", line 2163, in executor
  File "brailleDisplayDrivers\freedomScientific.pyc", line 500, in display
ValueError: bytes must be in range(0, 256)

Thanks

Andrey

**Comment by Andre9642** [comment]
Hmm, curious bug. Could you disable the option "Show punctuation/symbol name for undefined characters if available" in Braille
Extender settings? Does the bug still occur?
Thanks for the report!

**Comment by Futyn-Maker** [comment]
> Could you disable the option "Show punctuation/symbol name for undefined characters if available" in Braille
> Extender settings? Does the bug still occur?

I've done it now. The bug doesn't occur without this option. I also should say that I use Russian language of NVDA and this symbol is in symbols.dic.

**Comment by Andre9642** [comment]
OK, I'm able to reproduce it as well. :) Just passed the NVDA interface to Russian and the output braille table to Uzbek. I'll fix it ASAP. Thanks again.

**Comment by Andre9642** [comment]
It should be fixed now. Could you test with the latest dev version? Thanks.

**Comment by Futyn-Maker** [comment]
Yes, it seems to work correctly. Now I get a description of undefined symbols. Many thanks to Your fast work!

Andrey
